### ISSUE TITLE
What is nwjs-iot about?

### ISSUE THREAD

**Issue by shamun** [nwjs/nwjs-iot#1]
Is nwjs-iot planned to have old Chromium version, less then version 46? 

- can it play Google chrome webstore apps as it dos with chromium?
- can it play MP4 videos?
- can it ignore the https:// opening http://  or http:// opening https://?
- can it have clear cache via command line?

**Comment by rogerwang** [comment]
Congratulations to issue #1!

@nwjs/iot team should be able to answer it...

**Comment by shamun** [comment]
OK - Thank you. 

I would prefer to make NodeWebKit based on Chromium 46. Because in Banks, Government project i have used Chromium 46 the most stable version yet. Where i can use Google chrome apps from webstore, ignore https:// running internally robotic api's http:// or http:// executing internally https:// without errors that they introduced now

**Comment by rogerwang** [comment]
@shamun NW.js issue should be submitted to the nwjs repo. Not here...

**Comment by shamun** [comment]
OK, Great. thank you.
